import { RouteInfo } from "./horizontal-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "accueil",
    title: "Tableau de bord",
    icon: "home",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/demande/listDemandes/",
    title: "Demande",
    icon: "inbox",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/signalisation/list-signalisation",
    title: "Signalisation",
    icon: "alert-octagon",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "Paramètres",
    icon: "settings",
    class: "has-arrow",
    ddclass: "column",
    extralink: false,
    submenu: [
      {
        path: "/parametres/typemateriel",
        title: " Types de matériel",
        icon: "mdi mdi-priority-low",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/parametres/listmateriel",
        title: "Matériel",
        icon: "mdi mdi-rounded-corner",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/parametres/listdossier",
        title: "Type de dossier",
        icon: "mdi mdi-select-all",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "users/listusers",
    title: "Utilisateurs",
    icon: "users",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "Reporting",
    icon: "bar-chart-2",
    class: "has-arrow",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "/statistiques/signalisation",
        title: "Signalisations",
        icon: "alert-octagon",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/statistiques/demande",
        title: "Demandes",
        icon: "mdi mdi-priority-low",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/statistiques/cumul",
        title: "Dossiers traités",
        icon: "mdi mdi-priority-low",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  }
];
